Fix double-log from double-super invocation
kigster/puma-daemon pull request #19
Opened 2023-05-15 18:26 UTC by jpr5

Per issue #18.

2023-05-19 17:47 UTC, jpr5 commented
Passes now.

2023-05-21 18:04 UTC, kigster requested changes
Let's make this a regular expression check that would be more resilient to future upstream changes. Then I'll merge it. Thank you for your contribution!

2023-05-21 18:04 UTC, kigster commented on lib/puma/daemon/runner_adapter.rb
> +              return if str == 'Use Ctrl-C to stop'
Let's change this to a regular expression match:

```ruby
return if str =~ /Ctrl-C/
```

2023-05-21 20:34 UTC, jpr5 commented
Alright.

2023-06-22 20:55 UTC, kigster approved these changes

2023-06-22 20:55 UTC, merged